### ISSUE TITLE
Authentication Sign in

### ISSUE THREAD

**Issue by me-jterhorst** [me-jterhorst/neueFische-capstone-inCased#13]
## Value statement - a requirement, not a solution

As a User
I need to be able to sign in 
so that I can create a user profile

## Description (Text, Scribble, Wireframe, Design)
02 Authentication / Sign In
[Wireframe](https://www.figma.com/file/9RoUnd9cJeJDNydZ1Z0YOI/Neue-Fische---Capstone---InCased?node-id=109%3A1940)
## Acceptance criteria

- [ ] A sign up field that checks for username, e-mail and password
- [ ] A sign up button that is eligable
- [ ] A back button that leads back to the home page
- [ ] A link to the login option if I missclicked

## Tasks

- [ ] Write for screen background
- [ ] Create Card Component
- [ ] Create Input Field component
- [ ] Create Headline 
- [ ] Create Sign in Button 
- [ ] Create Backbutton
- [ ] Text and login link

## Size

medium
