### ISSUE TITLE
Create new task Step 1

### ISSUE THREAD

**Issue by me-jterhorst** [me-jterhorst/neueFische-capstone-inCased#16]
## Value statement - a requirement, not a solution

As a User
I need a way to create tasks
so that I can use the main feature

## Description (Text, Scribble, Wireframe, Design)
03 Create / Step 1 & Step 2
[Wireframes](https://www.figma.com/file/9RoUnd9cJeJDNydZ1Z0YOI/Neue-Fische---Capstone---InCased?node-id=109%3A1940)

## Acceptance criteria

- [ ] The app needs to feature a way to cancel my actions
- [ ] Needs an input field that also works with speech to text
- [ ] It needs to have a way to cycle through entries and change them in case there was an error
- [ ] Creating a task should create a new database entry. 
- [ ] Should support multiple actions
- [ ] User needs to be informed if input field is filled out wrong. 

## Tasks

- [ ] Add new Icon to back to Home route
- [ ] Change wording of some text
- [ ] Create new Input component
- [ ] Create new Add new button
- [ ] Temporarilly save the user input, so that fields can be cycled through before adding
- [ ] Add extra styling for an optional field
- [ ] Add regEx to prevent faulty inputs like code injection 

## Size

large
