### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by me-jterhorst** [me-jterhorst/neueFische-capstone-inCased#17]
## Value statement - a requirement, not a solution

As a User
I need a way to see all my created tasks in a list
so that I can choose which one I want to look at

## Description (Text, Scribble, Wireframe, Design)
04 Overview 
[Wireframes](https://www.figma.com/file/9RoUnd9cJeJDNydZ1Z0YOI/Neue-Fische---Capstone---InCased?node-id=109%3A1940)

## Acceptance criteria

- [ ] Filterable List
- [ ] Speech to text as an option to filter
- [ ] Drag to delete function
- [ ] Have a small icon display the number of actions inside a case

## Tasks

- [ ] Create new background
- [ ] Create List Item Component
- [ ] Implement Filtered List

## Size

medium
