### ISSUE TITLE
Single Frame

### ISSUE THREAD

**Issue by me-jterhorst** [me-jterhorst/neueFische-capstone-inCased#18]
## Value statement - a requirement, not a solution

As a User
I need way to access the details of my event
so that I can see my actions and add or delete actions

## Description (Text, Scribble, Wireframe, Design)
05 Single Frame
[Wireframes](https://www.figma.com/file/9RoUnd9cJeJDNydZ1Z0YOI/Neue-Fische---Capstone---InCased?node-id=109%3A1940)
## Acceptance criteria

- [ ] A way to traverse back and forth through different actions 
- [ ] A headline with the Event Trigger
- [ ] Input fields that have the value of their respective object fields
- [ ] A way to delete the the specific task
- [ ] An overview about how many elements there are
- [ ] Skip the first step from the create process and add a new action immediately

## Tasks

- [ ] Create a new Headline Component Style
- [ ] Change the Inputfield.value behaviour
- [ ] Create a Delete Item Button
- [ ] Create a new Add Action Button

## Size

medium
