### ISSUE TITLE
Account page

### ISSUE THREAD

**Issue by me-jterhorst** [me-jterhorst/neueFische-capstone-inCased#19]
## Value statement - a requirement, not a solution

As a User
I need an account overview page 
so that I can change Account settings 

## Description (Text, Scribble, Wireframe, Design)
07 Account
[Wireframes](https://www.figma.com/file/9RoUnd9cJeJDNydZ1Z0YOI/Neue-Fische---Capstone---InCased?node-id=109%3A1940)
## Acceptance criteria

- [ ] Overview of all Accountdetails
- [ ] Back Navigation to the Homescreen
- [ ] Delete Button that triggers modal to confirm that the delete action was meant to happen

## Tasks

- [ ] GET request to receive Data from Account Object
- [ ] PUSH request and conditional logic that checks if action is valid
- [ ] DELETE request and confirmation mechanic to see if it was meant to happen
- [ ] Create new background

## Size

medium
