### ISSUE TITLE
Imprint

### ISSUE THREAD

**Issue by me-jterhorst** [me-jterhorst/neueFische-capstone-inCased#20]
## Value statement - a requirement, not a solution

As a Product Owner
I need an imprint screen
so that I wouldn't make myself liable

## Description (Text, Scribble, Wireframe, Design)
08 Imprint
[Wireframes](https://www.figma.com/file/9RoUnd9cJeJDNydZ1Z0YOI/Neue-Fische---Capstone---InCased?node-id=109%3A1940)
## Acceptance criteria

- [ ] Create an imprint that is scrollable 
- [ ] Have an option to go back 

## Tasks

- [ ] Create a new background
- [ ] Change the component to allow it scroll

## Size

small
