### ISSUE TITLE
06 Menu

### ISSUE THREAD

**Issue by me-jterhorst** [me-jterhorst/neueFische-capstone-inCased#21]
## Value statement - a requirement, not a solution

As a User
I need a slide in Menu
so that I have a way to access different pages that are not that crucial

## Description (Text, Scribble, Wireframe, Design)
06 Menu
[Wireframes](https://www.figma.com/file/9RoUnd9cJeJDNydZ1Z0YOI/Neue-Fische---Capstone---InCased?node-id=109%3A1940)

## Acceptance criteria

- [x] A Menu that is hidden at first and slides in

## Tasks

- [x] A nav component with a darkmode, an account, an imprint and a sign in / login link
- [x] Have the menu toggle on click

## Size

small
