### ISSUE TITLE
Bottom Nav

### ISSUE THREAD

**Issue by me-jterhorst** [me-jterhorst/neueFische-capstone-inCased#24]
## Value statement - a requirement, not a solution

As a User
I need tab navigation at the bottom
so that I can navigate to the main sites in my app
## Acceptance criteria

- [x] Always there
- [x] Active Tab needs to be highlighted
- [x] Can incorporate the speech button

## Tasks

- [x] Create a footer element
- [x] Home nav
- [x] Create nav
- [x] Overview nav
- [x] Give tab the active class
- [x] Style the active class
- [x] Optional speech button

## Size

small
