### ISSUE TITLE
Basic Routing

### ISSUE THREAD

**Issue by me-jterhorst** [me-jterhorst/neueFische-capstone-inCased#25]
## Value statement - a requirement, not a solution

As a User
I need a way to move between different subpages
so that I can access them

## Description (Text, Scribble, Wireframe, Design)

Page content changes according to the

## Acceptance criteria

- [ ] Transition between pages

## Tasks

- [x] Implement Switch and Routes
- [ ] Build basic sites to switch to

## Size

small
